-- Batch 1 security: trusted audit logging.
-- Audit records must be generated by server-side operations, not freely
-- insertable by ordinary members. Clients append via the SECURITY DEFINER RPC
-- below, which stamps the authenticated actor and validates membership.

drop policy if exists "Users can insert their own audit logs" on public.audit_logs;
drop policy if exists "Team members can insert audit logs" on public.audit_logs;

create or replace function public.write_audit_log(
  p_business_id uuid,
  p_action text,
  p_details jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_business_id is not null and not public.is_business_member(p_business_id) then
    raise exception 'Not a member of this business';
  end if;

  insert into public.audit_logs (user_id, business_id, action, details)
  values (auth.uid(), p_business_id, p_action, p_details);
end;
$$;

grant execute on function public.write_audit_log(uuid, text, jsonb) to authenticated;

-- Membership and subscription changes also record their own audit rows
-- inside their SECURITY DEFINER functions (change_member_role, remove_member,
-- accept_invite_code) so the actor is always the authenticated user.
